baseURL = '/'
languageCode = 'en-us'
title = 'Reeve Blake'
theme = 'terminal'

[params]

contentTypeName = "posts"
themeColor = "blue"
showMenuItems = 2
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
autoCover = false
showLastUpdated = false

[module]

[[module.imports]]
path = 'github.com/reeve567/hugo-theme-terminal'