baseURL = '/'
languageCode = 'en-us'
title = 'Reeve Blake'
#theme = 'terminal'

[params]

contentTypeName = "posts"
themeColor = "blue"
showMenuItems = 2
showLanguageSelector = false
fullWidthTheme = false
centerTheme = false
autoCover = false
showLastUpdated = false

[module]

[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v3'